version: '3.8'

services: 
  db:
    # container_name: db
    # container_name: bluediamond_db
    image: mysql
    restart: always
    env_file: ./.env
    environment:
      MYSQL_DATABASE: 'ecommerce'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: '123456'
      MYSQL_ROOT_PASSWORD: '123456'
    
    ports:
      - "3306:3306"
    expose:
      # Opens port 3306 on the container
      - '3306'
    # networks:
    #   - backend
    volumes: 
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
      - ./db/backup/files/:/data_backup/data
    # networks:
    #   - backend
  app:
    depends_on:
      - db
    build: .
    env_file: ./.env
    ports:
      - 3000:3000
    volumes: 
      - ./app:/app
    stdin_open: true
    tty: true

volumes: 
  db-config:
  db-data:

# networks:
#   backend: